### ISSUE TITLE
Facet query with "facet.sort": "count" not returning sorted facets

### ISSUE THREAD

**Issue by Kerruba** [moonlitesolutions/SolrClient#33]
Hello,
I'm trying to submit this query to Solr Core with SolrClient, but the expected result object doesn't match the query since keys are not sorted by facet count. 
Here the query object passed to SolrClient:
```python
onto_suggest = solr.query('merged', {
	"q": "*:*",
	"rows": 0,
	"facet": True,
	"facet.field": "onto_suggest",
	"facet.sort": "count",
	"facet.limit": -1,
	"facet.mincount": 2
})
```
I've also tried to use "facet.count" to sort, same result.
Here an excerpt of the result
```python
{
  "onto_suggest": {
    "Arthrobacter siderocapsulatus": 433,
    "Enterobacter aglomerans": 39,
    "Genetic endocrine tumor": 32,
    "ETOP": 15,
    "lymphoid lineage restricted progenitor cell": 47,
    "Escherichia coli O157:H7 EDL933": 127,
    "deferoxaminum": 2,
    "Bacillus francki": 472,
    "srf": 9,
    "Malignant Peripheral Nerve Sheath Tumors": 9,
    "Pancreas Cancer": 122,
```

**Comment by nickvasilyev** [comment]
Hi, 

That method returns a regular python dictionary; it's main goal is to just pull it from the response. However, as I am sure you know python dictionaries aren't sorted. You can very easily sort it yourself when you retrieve the data though:


`d = {
    "Arthrobacter siderocapsulatus": 433,
    "Enterobacter aglomerans": 39,
    "Genetic endocrine tumor": 32,
    "ETOP": 15,
    "lymphoid lineage restricted progenitor cell": 47,
    "Escherichia coli O157:H7 EDL933": 127,
    "deferoxaminum": 2,
    "Bacillus francki": 472,
    "srf": 9,
    "Malignant Peripheral Nerve Sheath Tumors": 9,
    "Pancreas Cancer": 122,}
>>> for k in sorted(d, key=d.get, reverse=True):
...     print(k)
... 
Bacillus francki
Arthrobacter siderocapsulatus
Escherichia coli O157:H7 EDL933
Pancreas Cancer
lymphoid lineage restricted progenitor cell
Enterobacter aglomerans
Genetic endocrine tumor
ETOP
srf
Malignant Peripheral Nerve Sheath Tumors
deferoxaminum



`

**Comment by Kerruba** [comment]
Thanks, 

could be an improvement making the returned dictionary sorted automatically if the query has a facet.sort key inside? Otherwise, practically that option is going to be not useful

**Comment by nickvasilyev** [comment]
Thanks for the feedback. 

That option is used by Solr to select what data to return. If you have 100 values, but you are only pulling out 10; the sorting will determine which 10 it is.
