### ISSUE TITLE
Using IndexQ with finalize=True can "overwhelm" todo directory

### ISSUE THREAD

**Issue by fortiema** [moonlitesolutions/SolrClient#36]
Been using SolrClient in my latest project and it is by far the cleanest SOLR api for python out there, so kudos for that! Hoping it will keep being developed and supported for the foreseeable future.

One thing I see that could be improved is that indexing multi-million set of documents using IndexQ and the finalize=True argument will lead to the todo/ directory being overwhelmed (impossible to 'ls' normally nor 'rm -rf' due to size of directory listing metadata). I was thinking about creating subfolders under todo/ and put data there instead, capping it at certain number (0.5M files, for ex.).

I understand that it is bad to proceed like this when you understand how it all works, but for first time users and non-experts this could actually prevent this unfortunate case.

**Comment by nickvasilyev** [comment]
Glad you like the client, tell your friends :) and  I definitely plan to continue working on it. 

Can you provide a bit more info about this? The purpose of IndexQ is to just handle bulking of data and save it to disk temporarily. So if you have some process feeding out small chunks of data that you want to index into Solr, you wouldn't do it one at a time, but instead create bigger batches and index those.  This is what this tool does for you so you don't have to worry about it. 

 If you pass 'size' argument to IndexQ when you are making it, you can specify the size of internal buffer that once met will be written to disk (in todo directory). However as the application is running, if you decide that for some reason you want to dump out the "buffer" of docs to disk without waiting for the queue to fill up, you can just run add(finalize=True) ( this definitely shouldn't be included for every request) and it will create a file with whatever it has so far. Let me know if this kind of makes sense.

**Comment by fortiema** [comment]
Well let's just say I have a 10M document set to index, and I add them to IndexQ 1-by-1. If I use finalize=True for each add call, this will result in the todo/ directory being flooded with small files, causing problems on some filesystems (vfat, ext3-4 for example) where eventually you will get an IOError.

Agreed that this is not very clever and you would for example only write off to disk for every 10k-100k documents, but I made the mistake at the very beginning and I was thinking about how this can be prevented.

Actually the thing that confused me into doing that was that the small snipped example in the documentation is using finalize=True, so maybe this is just a matter of clarifying that!

**Comment by nickvasilyev** [comment]
Thanks man, that's actually a pretty good point. I know documentation is a bit lacking and haven't been updated recently. Want to take a stab at it?

**Comment by fortiema** [comment]
Sure thing, as soon as I get a chance I can surely suggest some improvements to the documentation and code format.
