### ISSUE TITLE
fix travic-ci , seems broken?

### ISSUE THREAD

**Issue by ddorian** [moonlitesolutions/SolrClient#39]
read title

**Comment by nickvasilyev** [comment]
I changed testing a while ago. A lot of modules require a live solr instance to test, plus I was running into issues with compatibility with multiple versions of Solr. 

Please check out this repo: 
https://github.com/moonlitesolutions/SolrVagrant

It's a vagrant box that downloads and installs several versions of Solr and sets it up with zookeeper and default collection configs. You can pull the branch down and execute a script that will test every module with every supported version of python against several versions of Solr. If something like this can be done with Travis, I would be all for it.

**Comment by ddorian** [comment]
I understand, but.. 
How to run the tests for the current git repo that exists on the computer, without commiting/pushing to github and changing ansible.raw_arguments? Is it possible ?(too much latency to commit/push/pull/test)

**Comment by nickvasilyev** [comment]
The /vagrant directory will mount to your local filesystem, it should have the code in there. This way, you can edit the code on your workstation, test it in vagrant and commit it only when ready. I was a bit tied up yesterday, but should be able to go through these changes today. Also, I found a bug in run_tests.py, for some reason tox wasn't installing dependencies from requirements.txt. If you run into the same issue, just modify run_tests.py and run "pip install -r requirements.txt" in the virtual env, once it gets created. I should get a fix for this in tonight as well.
