### ISSUE TITLE
_route_ to correct shard ?

### ISSUE THREAD

**Issue by ddorian** [moonlitesolutions/SolrClient#40]
Example, I was thinking of also adding:
1. method getting cluster state
2. keep track of hash-->shard-->host linking
3. when _route_ is specified, route directly to correct node(with failover to replicas)
3.1. route directly to leader for create,update,delete
4. prefer_leader=True will always contact leader of shard first and then replicas.
5. prefer_leader=False will contact leader last
6. prefer_leader=None will random.choice(replicas)
7. when multiple _route_ are added "tenant1,tenant2,tenant3", pick random replica to contact

Makes sense ?

The whole point is to contact minimum amount of nodes necessary, reducing network hops/traffic, lowering cpu.

**Comment by nickvasilyev** [comment]
I am not sure if this actually make any difference in performance from the client side. Do you see a performance difference? I run a 230k searches per day search cluster and haven't noticed anything. 

One case where this would be interesting though is with indexing. Indexing can be directed at a single node, multiple nodes (secondary hit if primary one fails), multiple nodes in parallel (like indexing into a DR site without CDCR). You can implement it if you really want to, but I doubt you would get any performance benefit from the query side. 

Additionally, there is a new collections and zookeeper module that can pull configs and some information like the clusterstate for you.

**Comment by nickvasilyev** [comment]
One major item on my todo list is SolrResponse, that module is very old and is a total mess. Unfortunately I still haven't gotten around to it.

**Comment by ddorian** [comment]
It's just an extra overhead (on client doing shard-selection or on solr passing requests around) and will matter depending on your qps + latency requirements.
Example running 1K+ queries/second in < 100ms.

My problem with indexing is that it's hard to guarantee stuff from the client-side(where was it accepted), but many people use that to migrate between indexes/type-of-databases/datacenters/whatevers. I meant _only_ routing, while you meant distributed-writes, which is a different thing.

**Comment by nickvasilyev** [comment]
Sounds like a good use case; go for it if you want to. 

On a side note; I like to have nginx between Solr and the app. Nginx provides some nice routing capabilities, lets me redirect all search queries to a different cluster entirely and has built in cache which is helpful if it is set up on the app server. Not sure if this will fit your use case, but wanted to throw it out there.

**Comment by ddorian** [comment]
2 issues with that for me:
1. I try to keep/maintain as few different pieces/type-of-software as possible. Ex: I use uwsgi with http-enabled and don't use nginx for the app.
2. Nginx still doesn't have a type of distributed caching backend as far as I know. So you have x nginx machines to proxy (either 1 in each app-server, 1 in each solr-server, or separate ones), each would have it's own local cache. And nginx still would have ~random load balancing (~just like calling that shuffle_hosts() before making a request).

Smart client ~is the way to go. Look at ~most nosql: cassandra,hbase,mongodb. Will matter a lot less when you do distributed-search though, since you'll hit ~all shards.
