### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by ddorian** [moonlitesolutions/SolrClient#41]
Some errors in the log. I stopped it after some time.

[solrtestslog.txt](https://github.com/moonlitesolutions/SolrClient/files/616957/solrtestslog.txt)

**Comment by nickvasilyev** [comment]
These are just some exceptions that it's catching and printing. There aren't too many other developers, so I enjoy getting a bit more insight into the tests. If you notice, all the tests checkout fine. It also prints a small report at the end for each test / solr version / python version. 

I am going to adjust the logging in the tests to make it a bit less verbose.
