### ISSUE TITLE
Test performance is very(extremly) slow

### ISSUE THREAD

**Issue by ddorian** [moonlitesolutions/SolrClient#42]
I have an i3 laptop with 8GB ram & SSD, and it was running very slow (taking up all ram & probably ). Any idea how we can:
1. make it faster
or
2. separate, so don't run tests for everything ?
or both ?

**Comment by nickvasilyev** [comment]
By default the vagrant box will use up 8 GB of RAM. I am not going to suggest you upgrade your box, but you can adjust the number of Solrs it installs in the Vagrant file. 

Once that is done, you will need to manually specify which solrs you want it to test. This can be done in run_tests.py. Here is a relevant code snippet:

`PYS = ['3.3', '3.4']
SOLRS = ['5.2.1', '5.5.3', '6.1.0', '6.2.1']
TESTS = ['test_client', 'test_indexq', 'test_reindexer', 'test_resp',
         'test_collections', 'test_zk']

parser = argparse.ArgumentParser()
parser.add_argument('-test', type=str, nargs='*', help='Which test.')
parser.add_argument('-solr', type=str, nargs='*', help='Which Solr.')
parser.add_argument('-py', type=str, nargs='*', help='PY')
args = parser.parse_args()

if args.test:
    TESTS = args.test
if args.solr:
    SOLRS = args.solr
if args.py:
    PYS = args.py
`

So if you wanted to run it for only solr 5.2.1 and only test_client, you can do something like this:

./run_tests.py -test solr_client -solr 5.2.1 

Hope this helps.
