### ISSUE TITLE
Please  update the PyPi package to reflect the latest changes

### ISSUE THREAD

**Issue by abhaykadam** [moonlitesolutions/SolrClient#54]
Hi,

My application code depends on the latest commit#a75912f73730d3aaaf64ca5684ab035c2666eedc where integer conversion step is removed. But, i  see the PyPi package of SolrClient doesn't have that issue fixed. Could you please update the PyPi package with the latest version.

Thanks,
Abhay

**Comment by nickvasilyev** [comment]
Done, 0.1.2 released.

**Comment by abhaykadam** [comment]
Thanks for quick response Nick!
