### ISSUE TITLE
Index calls itself recursively

### ISSUE THREAD

**Issue by lannyday** [moonlitesolutions/SolrClient#65]
https://github.com/moonlitesolutions/SolrClient/blob/master/SolrClient/solrclient.py#L130-L142.

My guess is that the code is intended to be:
```
data = json.dumps(docs)
return self.index_json(collection, data, params, **kwargs)
```

**Comment by lannyday** [comment]
I see (belatedly) that both open PR's attempt to address this issue.

**Comment by nickvasilyev** [comment]
Yikes.... 

Thanks for another ping on this, kind of dropped the ball on that PR for a while.
