### ISSUE TITLE
Multiple faceted fields?

### ISSUE THREAD

**Issue by selvianl** [moonlitesolutions/SolrClient#72]
Hello I am using SolrClient in my project.
I want to make faceted fields multiple by using `res.get_facet_keys_as_list`, I mean I wanna see more fields.
However, it is not correlated with Solr syntax.
In Solr, it is used like this:
`"fl":"genres,movie_title,title_year"`
Is there any possibility to make it ?
Thanks

**Comment by nickvasilyev** [comment]
Hi,

Solr's fl and facets are two different things. fl specifies which fields to pull in from the documents that are coming back, facets parameters specify which fields to run facet operations on. get_facet_keys_as_list runs on the facet response and just gives you a list of keys. If you want to include multiple facets, just send your request like:
'facet.field':['field1', 'field2']

Then get individual lists like:
res.get_facet_keys_as_list('field1')
res.get_facet_keys_as_list('field2')

Hope it helps.

**Comment by selvianl** [comment]
Cool explanation. Thanks for fast reply and information.

**Comment by nickvasilyev** [comment]
No problem, here to help.
